---

- name: Router_IP_Config
  hosts: Router
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Set Ethernet0/1 IPv4 address
      ios_config:
        lines: "{{ desc1 }}"
        parents: Interface Ethernet0/1
       
    - name: Set Ethernet0/2 IPv4 address
      ios_config:
        lines: "{{ desc }}"
        parents: Interface Ethernet0/2

    - name: Show ip
      ios_command:
        commands: 
          - show ip int brief | inc up
      register: show_ip
    - debug: var=show_ip.stdout_lines
   
