---

desc:
  - description R1-To-R2
  - ip address 192.168.12.1 255.255.255.0
  - no shutdown
  - exit  

desc1:
  - description R1-To-LAN
  - ip address 192.168.1.1 255.255.255.0
  - no shutdown
  - exit

static:
  - ip: 192.168.2.0
    nexthop: 192.168.12.2
    netmask: 255.255.255.0

ping:
  - ip_dest: 192.168.2.10
    ip_source: 192.168.1.1
